### PR TITLE
Updating plugin to use new Google Play Music API

### PR DESCRIPTION
**Pull request by mitchhymel**
I made the following changes to the plugin:
- Rewrote the Google Play Music API (https://github.com/mitchhymel/GooglePlayMusicAPI) to use OAuth2 for login
- Modified the plugin window to be colored the same as current MusicBee skin

### CODE REVIEW

**Comment by mitchhymel** [comment]
I've only tested through my own personal use, but everything seems to be working ok. Feel free to try it out and let me know if anything is broken: https://github.com/mitchhymel/MBGmusicSync/releases

**Comment by leoedin** [comment]
Thanks for this work. Seems to work on my end (although using it was a good reminder that the UI needs quite a lot of work).

**Comment by genrl** [comment]
Hi, thanks for all the work on the plugin guys. I've had some issues trying to use it, however, Followed the readme but when I click on configure in the plugin section on MusicBee I just get an info window telling me about the app, with no options other than OK. Thanks for your help

**Comment by mitchhymel** [comment]
The instructions you followed are necessary to enable the plugin, however, to get to the playlist sync window, you actually need to go to "Tools" -> "Google Music Playlist Sync".

The readme is not super clear here, so we may need to update that.

image

**Comment by genrl** [comment]
Thanks so much for your quick reply! No, my fault, only downloaded Musicbee
yesterday the other day so not fully across it. This should do the trick,
thanks again for all your work

**Pull request merged**
